// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf3zk8g8Djuxe2M9R946Gpmf3HIJ62QNA',
    appId: '1:817211044597:android:5f6cd0461f6369d72ccbbc',
    messagingSenderId: '817211044597',
    projectId: 'ai-image-analysis',
    databaseURL: 'https://ai-image-analysis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ai-image-analysis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy5VvPvjiWUI93A91_WMzM_a-O0H3V47E',
    appId: '1:817211044597:ios:495f499d588bd6752ccbbc',
    messagingSenderId: '817211044597',
    projectId: 'ai-image-analysis',
    databaseURL: 'https://ai-image-analysis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ai-image-analysis.appspot.com',
    iosBundleId: 'com.example.aiImageAnalysis',
  );
}
